### ISSUE TITLE
Files being unprocessed with the same last modified timestamp

### ISSUE THREAD

**Issue by kaisecheng** [logstash-plugins/logstash-input-s3#221]
The precision of S3 timestamp is in second. Files with the same `last_modified` could be processed in two iterations. However, for every processed file, the timestamp will be written in sincedb. In the next iterations, if the timestamp is smaller or equal (<=) to sincedb, files will be left unprocessed. Therefore from time to time, users see some files with the same timestamp remain to unpick. 

Related PR
https://github.com/logstash-plugins/logstash-input-s3/issues/57
https://github.com/logstash-plugins/logstash-input-s3/pull/189
https://github.com/logstash-plugins/logstash-input-s3/pull/61
https://github.com/logstash-plugins/logstash-input-s3/pull/192

**Comment by kaisecheng** [comment]
Fixed in v3.6.0

**Comment by yogevyuval** [comment]
@kaisecheng This is great, but is it merged into logstash? meaning which version of logstash uses the new plugin?

**Comment by kaisecheng** [comment]
@yogevyuval  Logstash 7.13

**Comment by sunfriendli** [comment]
The problem still exists in logstash-8.2.3 with logstash-input-s3 on 3.8.3. Files with same  last modified timestamp may be ignore, and thereby lead to data lost.

**Comment by kaisecheng** [comment]
@sunfriendli Could you create a new issue in this repo with reproducing steps and log for further investigation?

**Comment by sunfriendli** [comment]
> @sunfriendli Could you create a new issue in this repo with reproducing steps and log for further investigation?

Hello @kaisecheng , I created a new issue at #244
